---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users/{user_id}/posts/{post_id}/comments":
    post:
      summary: Creates a comment
      tags:
      - Comments
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      - name: post_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: comment created
        '422':
          description: invalid request
        '404':
          description: post not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
              required:
              - text
    get:
      summary: show all comments
      tags:
      - Comments
      parameters:
      - name: post_id
        in: path
        required: true
        schema:
          type: string
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: show all comments
        '404':
          description: post not found
  "/api/v1/users/{user_id}/posts":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    get:
      summary: list posts
      tags:
      - Posts
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
        '404':
          description: user not found
  "/api/v1/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
